name: coffee_life
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Icons & Fonts
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0

  #Native Splash
  flutter_native_splash: ^2.4.0

  #Launcher Icons
  flutter_launcher_icons: ^0.13.1

  #Utils
  connectivity_plus: ^5.0.2
  dio: ^5.4.3+1
  cached_network_image: ^3.3.1
  smooth_page_indicator: ^1.1.0
  image_picker: ^1.1.0
  lottie: ^3.1.0
  shimmer: ^3.0.0
  intl: ^0.19.0

  #Firebase
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  firebase_storage: ^11.7.6
  cloud_firestore: ^4.17.4

  #State Management
  get: ^4.6.6
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

